### ISSUE TITLE
prepare_mpbcalc does not take KPathInterpolant object

### ISSUE THREAD

**Issue by samuelkim314** [thchr/MPBUtils.jl#3]
The `prepare_mpbcalc` function does not take a `KPathInterpolant` object for the `kvecs` argument. An example code excerpt is below (not meant to be a MRE)

```
runtype="all"
sgnum = 68
cntr = centering(sgnum, 3) # centering symbol (e.g, 'F' for face-centered, etc.)
Rs = conventionalize(pRs, cntr)
kp = irrfbz_path(sgnum, Rs)
k_interp = interpolate(kp, 1000)
kvecs = k_interp

prepare_mpbcalc!(io, sgnum, pflat, pRs, nothing, epsin, epsout, runtype;
            isoval=isoval, res=32, kvecs=kvecs, id=nothing, nbands=6)
```
which gives the error
```
ERROR: LoadError: TypeError: in keyword argument kvecs, expected Union{Nothing, AbstractString, AbstractVector{var"#s31"} where var"#s31"<:(Vector{var"#s32"} where var"#s32"<:Real)}, got a value of type KPathInterpolant{3}
```

The `kvecs` argument is supposed to be a string (that would be printed to the MPB input file) or an array of vectors representing the list of k-vectors.

A simple workaround is to convert the `KPathInterpolant` through the following line before passing it into `prepare_mpbcalc`
```
kvecs = [Array(kvec) for kvec in k_interp] # Restructure
```

This could be added into MPBUtils.jl, but I think it would add a dependency on Brillouin.jl to detect the KPathInterpolant type, so I am opening this issue as a reminder.

**Comment by thchr** [comment]
Hmm, this is a little bit subtle. The problem seems to be that I at some point deprecated the `kvecs` argument in favor of `kvs` and at the same time extended the type-signature of `kvs` but not for `kvecs`: see [here](https://github.com/thchr/MPBUtils.jl/blob/9fa3ca6f43882857b98d3da9acd106c20c455d8f/src/export2mpb.jl#L121-L122).
Ideally, we'll all stop using the `kvecs` argument and just use `kvs` - but in the meantime, I can upload a fix that just extends the argument type from `Union{..., AbstractVector{<:Vector{<:Real}}}` to ``Union{..., AbstractVector{<:AbstractVector{<:Real}}}`.

**Comment by thchr** [comment]
Can you confirm that https://github.com/thchr/MPBUtils.jl/commit/b20c62c644676df08af79b014fd7e95e84578195 fixes the issue?

**Comment by samuelkim314** [comment]
Thanks, I can confirm this fixes the issue! I will also use `kvs` instead of `kvecs`. It looks like in the code it's just a renaming, is that right?

**Comment by thchr** [comment]
It's just renaming, yeah: I honestly don't even remember why I changed it - maybe there was some inconsistency across various kwarg names?
